apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: patricia-app
  labels: { app: auth }
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: auth }
  template:
    metadata:
      labels: { app: auth }
    spec:
      serviceAccountName: auth
      containers:
        - name: auth
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef: { name: auth-config }
            - secretRef:    { name: auth-secrets }
          readinessProbe:
            httpGet: { path: /auth/health, port: 8081 }
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /auth/health, port: 8081 }
            initialDelaySeconds: 40
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
